name: 'Keeper Secrets Manager Github Action'
description: 'A GitHub Action to consume secrets from Keeper'
inputs:
  keeper-secret-config:
    description: 'Keeper Secrets Manager configuration json'
    required: true
  secrets:
    description: 'A list of secrets to retrieve from Keeper Vault'
    required: true
outputs:
  secret:
    description: 'The KSM secret'
runs:
  using: node12
  main: 'dist/index.js'